### PR TITLE
Complete conversion (with warning) even if EXIF data is missing.

### PR DESCRIPTION
**Pull request by bcherry**
This resolves https://github.com/monostream/tifig/issues/54

### CODE REVIEW

**Comment by adrianliechti** [comment]
thanks a lot!

**Comment by bcherry** [comment]
@adrianliechti thanks for accepting my PR so quickly! 

I'm having a hell of a time generating a build that's compatible with the static builds you provide, are you able to publish a new version? We'd like to get this fix into production but so far I've been unable to make a build we can drop in place.

**Comment by adrianliechti** [comment]
good question :)
I think this was built in a https://github.com/phusion/holy-build-box

have you tried to build with the dockerfile and copy the binary?

(on your linux/mac machine)
$ docker build -t tifig .
$ docker run -it --rm -v $(pwd):/out tifig /bin/ash

(in the container)
$ cp tifig /out
$ exit 

now you should find a linux binary in your working dir:
-rwxr-xr-x   1 adrian  staff  1227736 Sep 16 19:45 tifig

does this one work for you?

**Comment by bcherry** [comment]
@adrianliechti yes - I did try that and it works generally but I haven't gotten it to work as a static build with all of the dependencies included.

**Comment by adrianliechti** [comment]
@Flask do you remember how the static build was done?
(i remember this strange holy-build-box....)

**Comment by Flask** [comment]
@adrianliechti @bcherry:  I've added the [build script](https://github.com/monostream/tifig/tree/master/static-build-script) we used back then – but it seems as they would need some love.

**Comment by bcherry** [comment]
thanks everyone, we got it built with help from @bantonj and @jtomson. they might send a PR your way with updated build instructions.

**Pull request merged**
